src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime')]
    private $published_date;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private $author;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class)]
    private $comments;

    #[ORM\Column(type: 'string', length: 255)]
    private $shortdescrition;

    #[ORM\Column(type: 'string', length: 255)]
    private $thumbnail;

    #[ORM\Column(type: 'boolean')]
    private $draft;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedDate(): ?\DateTimeInterface
    {
        return $this->published_date;
    }

    public function setPublishedDate(\DateTimeInterface $published_date): self
    {
        $this->published_date = $published_date;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getShortdescrition(): ?string
    {
        return $this->shortdescrition;
    }

    public function setShortdescrition(string $shortdescrition): self
    {
        $this->shortdescrition = $shortdescrition;

        return $this;
    }

    public function getThumbnail(): string
    {
        return $this->thumbnail;
    }

    public function setThumbnail(string $thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getDraft(): ?bool
    {
        return $this->draft;
    }

    public function setDraft(bool $draft): self
    {
        $this->draft = $draft;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre'
            ])
            ->add('shortdescrition', TextType::class, [
                'label' => 'Description courte'
            ])
            ->add('thumbnail', FileType::class, [
                'label' => 'Votre image',
                'data_class' => null,
                'required' => false,
                'mapped' => false
            ])
            ->add('content', CKEditorType::class, [
                'label' => 'Votre Article',
                'constraints' => [
                    new Length([
                        'min' => 40,
                        'max' => 1500,
                    ]),
                ],
            ])
            ->add('draft', ChoiceType::class, [
                'label' => 'Est-ce un brouillon ?',
                'choices' => [
                    'Oui'=> false,
                    'Non' => true
                ]
            ])
            ->add('Publier', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Entity\User;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article')]
    public function index(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->findAll();
        return $this->render('article/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    #[Route('/article/add', name: 'add_article')]
    #[IsGranted('ROLE_AUTHOR')]
    public function add(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() ) {


            $file = $form['thumbnail']->getData();
            $ext = $file->guessExtension();
            if (!$ext) {
                $ext = 'bin';
            }

            $fileName = $file->getClientOriginalName().uniqid();
            $file->move('thumbnail', $fileName);
            $article->setThumbnail( $fileName);

            $article->setAuthor($this->getUser());
            $article->setPublishedDate(new \DateTime());

            $entityManager->persist($article);
            $entityManager->flush();

           return $this->redirectToRoute('app_article');
        }

        return $this->render('article/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/article/{id}', name: 'article_id')]
    public function showArticleById(Article $article,Request $request, EntityManagerInterface $entityManager)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $comment->setAuthor($this->getUser());
            $comment->setArticle($article);
            $comment->setDate(new \DateTime());

            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute("article_id", ["id" => $article->getId()]);

        }

        return $this->render('article/articleById.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    #[IsGranted('ROLE_AUTHOR')]
    #[Route('/article/edit/{id}', name: 'article_edit')]
    public function edit(Article $article, Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $oldImg = $article->getThumbnail();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $imageFile = $form['thumbnail']->getData();

            if (!empty($imageFile)) {

                $fileName = $imageFile->getClientOriginalName().uniqid();
                $imageFile->move('thumbnail', $fileName);
                $article->setThumbnail($fileName);

            }

            else {
                $article->setThumbnail($oldImg);
            }

            $entityManager->persist($article);
            $entityManager->flush();
            return $this->redirectToRoute('app_user');
        }

        return $this->render('article/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[IsGranted('ROLE_AUTHOR')]
    #[Route('article/delete/{id}', name: 'article_delete')]
    public function del(Article $article, EntityManagerInterface $entityManager) {

        $entityManager->remove($article);
        $entityManager->flush();


        return $this->redirectToRoute('app_user');
    }
}

templates/article/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un article{% endblock %}

{% block body %}
    {{ form(form) }}
{% endblock %}

templates/article/articleById.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome !{% endblock %}

{% block body %}
    <div class="articleIdContainer">
        <div class="divTitle">
            <h1>{{ article.title }}</h1>
            <p>Ecrit par {{ article.author.username }} le {{ article.publishedDate.getTimestamp()|date }}</p>
        </div>
        <div class="articleContent">
            {{ article.content|raw }}
        </div>
        <div class="commentContainer">
            {% for comment in article.comments %}
                <div class="commentContentContainer">
                    <h2><img class="avatar" src="/avatar/{{ comment.author.avatar }}"> {{ comment.author.username}}</h2>
                    <h4>{{ comment.date|date }}</h4>
                    <p>{{ comment.content }}</p>

                    {% if ('ROLE_MODERATOR' in app.user.roles) or (app.user == comment.author) %}
                        <a href="{{ path('comment_remove', {'id': comment.id}) }}">Delete</a>
                    {% endif %}

                </div>
            {% endfor %}
        </div>
    </div>

    {% if app.user %}
        {{ form(form) }}
    {% endif %}

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome !{% endblock %}

{% block body %}

    <div class="divTitle">
        {% if app.user %}
            <h1>Bien le bonjour {{ app.user.username }}</h1>
            <button id="buttonProfil"><a href="{{ path('app_user') }}">Profil</a></button>
            <button id="buttonLogOut"><a href="{{ path('app_logout') }}">Se déconnecter</a></button>


        {% else %}
            <h1>Bonjour !</h1>
            <ul>
                <li>
                    <button>
                        <a href="{{ path('app_login') }}">Se connecter</a>
                    </button>
                </li>
                <li>
                    <button>
                        <a href="{{ path('app_register') }}">S'inscrire</a>
                    </button>
                </li>
            </ul>
        {% endif %}
    </div>

    <div class="mainContainer">

        {% for article in articles %}
            {% if article.draft %}
                <div class="articleContainer">
                    <div>
                        <img src="/thumbnail/{{ article.thumbnail }}">
                    </div>
                    <div>
                        <a href="{{ path('article_id', {'id': article.id}) }}">{{ article.title }}</a>
                        <h3>Publié le {{ article.getPublishedDate().getTimestamp()|date }}
                            par <img class="avatar" src="/avatar/{{ article.author.avatar }}">{{ article.author.username }}</h3>
                        <div>
                            {{ article.shortdescrition}}...
                        </div>
                    </div>

                </div>
            {% endif %}
        {% endfor %}
    </div>



{% endblock %}